#!/bin/bash

trap 'exit 130' INT

read -rp "Search: " query

mapfile -t results < <(
  yt-dlp "ytsearch20:${query}" \
    --flat-playlist \
    --print $'%(title)s\t%(id)s\t%(duration_string)s'
)

[[ ${#results[@]} -eq 0 ]] && {
  echo "No results."
  exit 1
}

idx=$(for i in "${!results[@]}"; do
  IFS=$'\t' read -r title _ dur <<<"${results[$i]}"
  printf '%d: %s [%s]\n' "$i" "$title" "$dur"
done | fzy -l 20 -p "Select: " | grep -o '^[0-9]*')

[[ -z "$idx" ]] && exit 0

IFS=$'\t' read -r _ id _ <<<"${results[$idx]}"
mpv --no-video "https://www.youtube.com/watch?v=$id"
